package fr.spse.components_plus.utils

import android.text.InputType.*

object SimpleInputType{
    const val DATE = TYPE_CLASS_DATETIME or TYPE_DATETIME_VARIATION_DATE
    const val DATETIME = TYPE_CLASS_DATETIME or TYPE_DATETIME_VARIATION_NORMAL
    const val NONE = 0
    const val NUMBER = TYPE_CLASS_NUMBER or TYPE_NUMBER_VARIATION_NORMAL
    const val NUMBER_DECIMAL = TYPE_CLASS_NUMBER or TYPE_NUMBER_FLAG_DECIMAL
    const val NUMBER_PASSWORD = TYPE_CLASS_NUMBER or TYPE_NUMBER_VARIATION_PASSWORD
    const val NUMBER_SIGNED = TYPE_CLASS_NUMBER or TYPE_NUMBER_FLAG_SIGNED
    const val PHONE = TYPE_CLASS_PHONE
    const val TEXT = TYPE_CLASS_TEXT or TYPE_TEXT_VARIATION_NORMAL
    const val TEXT_AUTOCOMPLETE = TEXT or TYPE_TEXT_FLAG_AUTO_COMPLETE
    const val TEXT_AUTOCORRECT = TEXT or TYPE_TEXT_FLAG_AUTO_CORRECT
    const val TEXT_CAP_CHARS = TEXT or TYPE_TEXT_FLAG_CAP_CHARACTERS
    const val TEXT_CAP_SENTENCES = TEXT or TYPE_TEXT_FLAG_CAP_SENTENCES
    const val TEXT_CAP_WORDS = TEXT or TYPE_TEXT_FLAG_CAP_WORDS
    const val TEXT_EMAIL_ADDRESS = TYPE_CLASS_TEXT or TYPE_TEXT_VARIATION_EMAIL_ADDRESS
    const val TEXT_MULTI_LINE = TEXT or TYPE_TEXT_FLAG_MULTI_LINE
    const val TEXT_LONG_MESSAGE = TYPE_CLASS_TEXT or TYPE_TEXT_VARIATION_LONG_MESSAGE
    const val TEXT_NO_SUGGESTIONS = TEXT or TYPE_TEXT_FLAG_NO_SUGGESTIONS
    const val TEXT_PASSWORD = TYPE_CLASS_TEXT or TYPE_TEXT_VARIATION_PASSWORD
    const val TEXT_PERSON = TYPE_CLASS_TEXT or TYPE_TEXT_VARIATION_PERSON_NAME
    const val TEXT_SHORT_MESSAGE = TYPE_CLASS_TEXT or TYPE_TEXT_VARIATION_SHORT_MESSAGE
    const val TEXT_URI = TYPE_CLASS_TEXT or TYPE_TEXT_VARIATION_URI
    const val TEXT_VISIBLE_PASSWORD = TYPE_CLASS_TEXT or TYPE_TEXT_VARIATION_VISIBLE_PASSWORD
    const val TEXT_WEB_EDIT_TEXT = TYPE_CLASS_TEXT or TYPE_TEXT_VARIATION_WEB_EDIT_TEXT
    const val TEXT_WEB_EMAIL_ADDRESS = TYPE_CLASS_TEXT or TYPE_TEXT_VARIATION_WEB_EMAIL_ADDRESS
    const val TEXT_WEB_PASSWORD = TYPE_CLASS_TEXT or TYPE_TEXT_VARIATION_WEB_PASSWORD
    const val TIME = TYPE_CLASS_DATETIME or TYPE_DATETIME_VARIATION_TIME
}